//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPKDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_Detail
    {
        public int ID { get; set; }
        public Nullable<int> Prescription_id { get; set; }
        public Nullable<int> Medicine_id { get; set; }
        public Nullable<int> Quanlity { get; set; }
        public Nullable<int> Morning { get; set; }
        public Nullable<int> Noon { get; set; }
        public Nullable<int> Afternoon { get; set; }
        public Nullable<int> Night { get; set; }
        public string Note { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
